resources:
  repositories:
  - repository: retype
    type: github
    endpoint: gdraheim
    name: ambv/retype
    ref: 04978c6f7dcedb76ff334da8d5be734d3a4ce4b4
#   ref: 17.12.0

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: retype
- script: |
    sudo apt-get update --fix-missing
  displayName: 'refresh install'
- script: |
    sudo apt-get install --fix-broken --ignore-missing python3-typed-ast mypy
  displayName: 'install python3 mypy'
- script: |
    sudo apt-get install --fix-broken --ignore-missing python3-coverage
  displayName: 'install python3 coverage'
- script: |
    sudo apt-get install --fix-broken --ignore-missing python3-pip
  displayName: 'install python3 pip'
- script: |
    pip3 install unittest-xml-reporting
  displayName: 'install unittest-xml-reporting'
- script: |
    pwd
    sed -i -e "s:test_runner.output.write(xml_content):test_runner.output.write(xml_content.decode('utf-8')):"  $HOME/.local/lib/python3.6/site-packages/xmlrunner/result.py
  displayName: 'patch unittest-xml-reporting'
- script: |
    find . -type d
  displayName: 'make type (mypy strict type checking)'
- script: |
    make type -C docker-systemctl-replacement
  displayName: 'make type (mypy strict type checking)'
- script: |
    make coverage -C docker-systemctl-replacement
    true
  displayName: 'make coverage (testsuite.py with coverage)'
- script: |
    find . -name '*.xml'
  displayName: 'find xml'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Basic Code Coverage (python3) without docker-based tests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    pathToSource: '$(System.DefaultWorkingDirectory)/docker-systemctl-replacement/'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
